version: 1
formatters:
  colorful:
    (): colorlog.ColoredFormatter
    format: "%(log_color)sRANK_%(rank)s - %(asctime)s - %(name)s - %(levelname)s - %(reset)s%(message)s"
    log_colors:
      DEBUG: white
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colorful # Use colorful formatter
  # file:
  #   class: logging.FileHandler
  #   level: INFO
  #   filename: test.log # Change to your desired log file name
  #   formatter: simple # Use simple formatter for the file
root:
  handlers: [console] # Attach both console and file handlers
  level: DEBUG
